#pragma once

#include "Career.h"

// Array de materias

// 0: Mencion General, 1: Mencion Programacion, 2: Mecion Inteligencia Artificial, 3: Mencion Mecatronica

Career subjectsAndOptionsPerCareer[3] = {
  "Ingenieria de Sistemas",
  {1, 6,{
  {"Matematica I", 3, 0},
  {"Logica Matematica", 3, 0},
  {"Geometria Analitica", 3, 0},
  {"Educacion fisica", 2, 0},
  {"Etica y Cultura Universitaria", 2, 0},
  {"Identidad y Expresion Cultura", 2, 0},
},
  2, 6 ,{
  {"Matematica II", 3, 0},
  {"Fisica I", 3, 0},
  {"Algebra Lineal", 3, 0},
  {"Procesos Basicos del P.",2,0},
  {"Introduccion a la Ingenieria", 2, 0},
  {"Informatica", 2, 0},
},
  3, 7,{
  {"Matematica III", 3, 0},
  {"Fisica II", 3, 0},
  {"Ciencia, tecnologia y sociedad", 2, 0},
  {"Mecanica", 2, 0},
  {"Quimica", 2, 0},
  {"Laboratorio de Fisica", 2, 0},
  {"Desarrollo Humano Integral", 2, 0},
},
  4, 5, {
  {"Matematica IV", 3, 0},
  {"Diseno Asistido por Computadora", 2, 0},
  {"Algoritmica", 3, 0},
  {"Teoria General de Sistemas", 2, 0},
  {"Mecanica de Fluidos", 2, 0},
},
  5, 6, {
	 {"Programacion I", 3, 0},
	{"Estadistica I", 3, 0},
	{"Arquitectura del Computador", 2, 0},
	{"Base de Datos", 2, 0},
	{"Analisis y Diseno de Sistemas", 2, 0},
	{"Calculo Numerico", 3, 0},
},
	6, 7, {
	{"Programacion II", 3, 0},
	{"Estadistica II", 3, 0},
	{"Analisis y Diseno de Sistemas II", 2, 0},
	{"Sistemas Operativos", 2, 0},
	{"Electronica", 2, 0},
	{"Ecologia y Desarrollo Productivo", 2, 0},
	{"Electiva", 2, 0},
},
	7, 7, {
	{"Programacion III", 3, 0},
	{"Base de Datos II", 2, 0},
	{"Investigacion de Operaciones", 3, 0},
	{"Analisis y Diseno de Sistemas III", 2, 2},
	{"Geopolitica", 2, 0},
	{"Modelaje y Simulacion", 2, 0},
	{"Electiva II", 2, 0}
},
	8, 8, {
	{"Programacion IV", 3, 0},
	{"Investigacion de Operaciones II", 3, 0},
	{"Introduccion a la Inteligencia Artificial", 2, 2},
	{"Comunicaciones I", 2, 0},
	{"Control I", 2, 0},
	{"Ingenieria de Software", 2, 1},
	{"Introduccion a la Ingenieria Biomedica", 2, 3},
	{"Introduccion a la robotica", 2, 2},
},
	9, 8, {
	{"Programacion V", 3, 0},
	{"Teoria y tecnicas de decision", 2, 0},
	{"Comunicaciones II", 3, 0},
	{"Control II", 2, 0},
	{"Auditoria de Sistemas", 2, 0},
	{"Procesamiento Digital de Imagenes", 2, 1},
	{"Informatica Medica", 2, 2},
	{"Sistemas Expertos y Logica Difusa", 2, 3},

},  10, 11, {
	  {"Sistemas de Transmision", 2, 0},
	  {"Ingenieria Economica", 2, 0},
	  {"Control Estadistico de Procesos", 2, 0},
	  {"Investigacion de Basica", 2, 0 },
	  {"Control Estadistico de Procesos", 2, 0},
	  {"Modelos Contables", 2, 1},
	  {"Tecnicas de Programacion Dinamica", 2, 1},
	  {"Biomedica", 2, 2},
	  {"Modelos y Simulacion de Biosistemas", 2, 2},
	  {"Introduccion a la Mecatronica", 2, 3},
	  {"Algoritmos Genericos", 2, 3},
}, 11, 10, {
{"Transmision de Datos", 2, 0},
{"Administracion y Gerencia", 2, 0},
{"Investigacion Aplicada", 3, 0},
{"Legislacion Laboral", 2, 0},
{"Sistemas Educativos", 2, 1},
{"Control y Calidad de Software", 2, 1},
{"Mantenimiento en Sistemas Biotecnologicos", 2, 2},
{"Sistemas de Control Biomedicos", 2, 2},
{"Redes Neuronales", 2, 3},
{"Computacion Cuantica", 2, 3},},
  12, 2, {
	  {"Practica Profesional", 7, 0},
	  {"Proyecto Socio-intregrador", 6, 0},
  },
},


	// 0: Mencion General, 1: Mencion Educativa, 2: Mencion Clinica, 3: Mencion Organizacional
	{"Psicologia",
{1, 6, {
   {"Psicologia General I", 3, 0},
	{"Estructura S. y C. Humano", 3, 0},
	{"Filosofia de la Psicologia", 3, 0},
	{"Identidad y Expresion Cultural", 2, 0},
	{"Educacion Fisica", 2, 0},
	{"Etica y Cultura Universitaria", 2, 0},
		
  },	2, 5, {
	{"Estadistica Aplicada a la Psicologia", 3, 0},
	{"Psicologia General II", 3, 0},
	{"Sistema Educativo Comparado", 3, 0},
	{"Psicologia Social", 3, 0},
	{"Procesos Basicos del Pensamiento", 2, 0},
},
  3, 5, {
	 {"Psicoestadistica",3, 0},
	 {"Neurociencias I", 3, 0},
	 {"Introduccion a la Psicologia Educacional", 3, 0},
	 {"Desarrollo Humano Integral", 2, 0},
	 {"Ciencia, Tecnologia y Sociedad",2, 0},
},
  4, 5, {
	  {"Psicometria I", 3, 0},
	 {"Neurociencias", 3, 0},
	 {"Psicologia de la Personalidad I", 3, 0},
	 {"Psicologia Comunitaria", 3, 0},
 {"Introduccion a la Psicologia Organizacional"},
},

 5, 6, {
	 {"Psicometria II", 3, 0,},
	 {"Psicologia de la Personalidad II", 3, 0},
	 {"Introduccion a la Psicologia Clinica", 3, 0},
	 {"Dinamica de Grupos Aplicadas", 2, 0},
	 {"Psicologia del Desarrollo I", 3, 3},
	 {"Practica de Psicologia del Desarrollo I", 3, 0},
},
  6, 6, {
	  {"Psicologia Experimental", 3, 0},
	 {"Psicologia del Desarrollo II", 3, 0},
	 {"Practica de Psicologia del Desarrollo II", 3, 0},
	 {"Psicopatologia I", 3, 0},
	 {"Electiva I", 2, 0},
	 {"Ecologia y Desarrollo Productivo", 2, 0},
},

 7, 6, {
	 {"Metodos e Instrumentos de Evalucacion Psicologica I", 3, 0},
	 {"Psicopatologia I", 3, 0},
	 {"Practica de Psicopatologia", 3, 0},
	 {"Psicologia Familiar", 3, 0},
	 {"Geopolitica", 2, 0},
	 {"Electiva II", 2, 0},
},
	 8, 12, {
	 {"Metodos e Intrumentos de Evaluacion Psicologica II ", 3, 0},
	 {"Psicologia de la Adiccion y la Dependencia", 3, 0},
	 {"Etica del Psicologo", 2, 0},
	 {"Psicologia Educacional I", 3, 1},
	 {"Neuroeducacion Aplicada al Aprendizaje", 3, 1},
	 {"Tecnicas Terapeuticas Aplicadas", 3, 1},
	 {"Psicologia Infanto-juvenil", 3, 2},
	 {"Practica de Psicologia Infanto-juvenil", 3, 2},
	 {"Psicologia Clinica", 3, 2},
	 {"Psicologia Organizacional I", 3, 3},
	 {"Neuropsicologia Organizacional", 3, 3},
	 {"Psicologia del Trabajo", 3, 3},
},
 9, 16, {
	 {"Innovacion y Pensamiento Creativo", 3, 0},
	 {"Psicologia Educacional II", 3, 1,},
	 {"Intervencion Psicoeducativa", 3, 1},
	 {"Practica de Intervencion Psicoeducativa", 3, 3},
	 {"Tendencias Digitales en Educacion", 3, 1},
	 {"Trastornos del Aprendizaje I", 3, 1},
	 {"Psicologia del Adulto", 3, 2,},
	 {"Practica de Psicologia del Adulto", 3, 2},
	 {"Neuropsicologia Clinica", 3, 2},
	 {"Tendencias Digitales en Psicologia Clinica", 3, 2},
	 {"Teoria de los Tratamientos I", 3, 2},
	 {"Psicologia Organizacional II", 3, 3},
	 {"Tendencias Digitales en las Organizaciones", 3, 3},
	 {"Tecnicas de Entrevistas Organizacionales", 3, 3},
	 {"Psicologia Empresarial", 3, 3},
	 {"Evaluacion Psicologica en las Organizaciones", 3, 3},
},

  10, 13, {
	 {"Investigacion Basica", 2, 0},
	 {"Gerencia Educacional", 3, 1},
	 {"Atencion a la Diversidad", 3, 1},
	 {"Trastornos del Aprendizaje II", 3, 1},
	 {"Estimulacion y Atencion Temprana", 3, 1},
	 {"Psicogerontologia", 3, 2},
	 {"Practica de Psicogerontologia", 3, 2},
	 {"Teoria de los Tratamientos II", 3, 2},
	 {"Psicologia de la Salud", 3, 2},
	 {"Desarrllo Organizacional", 3, 3},
	 {"Practica de Intervencion Organizacional", 3, 3},
	 {"Captacion Seleccion e Induccion del Talento Humano", 3, 3},
	 {"Tecnicas de Evaluacion del Desempeno", 3, 3},
},
  11, 8, {
	 {"Legislacion Laboral", 3, 0},
	 {"Investiacion Aplicada", 3, 0},
	 {"Supervision y Evaluacion Institucional", 3, 1},
	 {"Psicologia de la Orientacion", 2, 1},
	 {"Sexologia", 3, 2},
	 {"Tecnicas Psicoterapeuticas", 2, 2},
	 {"Desarrollo y Formacion del Talento Humano", 3, 3},
	 {"Psicologia de la Sociedad Ocupacional", 2, 3},

},
  12, 2, {
	 {"Practica Profesional", 7, 0},
	 {"Proyecto Socio-integrador", 6, 0},
},

  }
  }, {
"Ingenieria Electrica", 
	  {1, 6, {
{"Matematica 1", 3, 0},
{"Logica Matematica", 3, 0},
{"Geometria Analitica", 3, 0},
{"Educacion fisica", 2, 0},
{"Etica y Cultura Universitaria", 2, 0},
{"Identidad y Expresion Cultura", 2, 0},
}, 2, 6 ,{
  {"Matematica II", 3, 0},
  {"Fisica I", 3, 0},
  { "Algebra Lineal", 3, 0 },
  { "Procesos Basicos del P.",2,0 },
  { "Introduccion a la Ingenieria", 2, 0 },
  { "Informatica", 2, 0 },
},
3, 7, {
{"Matematica III", 3, 0},
{"Fisica II", 3, 0},
{"Ciencia, tecnologia y sociedad", 2, 0},
{"Mecanica", 2, 0},
{"Quimica", 2, 0},
{"Laboratorio de Fisica", 2, 0},
{"Desarrollo Humano Integral", 2, 0 },
 },
 4, 5, {
 {"Matematica IV", 3, 0},
 {"Diseno Asistido por Computadora", 2, 0},
 {"Algoritmica", 3, 0},
 {"Teoria General de Sistemas", 2, 0},
 {"Mecanica de Fluidos", 2, 0},
 },
 5, 5, {
 {"Matematica V", 3, 0},
 {"Redes Electricas I", 4, 0},
 {"Estadistica Aplicada", 3, 0},
 {"Mediciones Electricas", 3, 0},
 {"Laboratorio de Mediciones Electricas", 2, 0},
},
 6, 6, {
 {"Redes Electricas II", 4, 0},
 {"Laboratorio de Redes Electricas", 2, 0},
 {"Fundamentos del Electromagnetismo", 4, 0},
 {"Electronica I", 3, 0},
 {"Ciencia de los Materiales",2, 0},
 {"Ecologia y Desarrollo Productivo", 2, 0},
},

7, 7, {
 {"Maquinas Electricas I", 3, 0},
	{"Electronica II", 3, 0},
	{"Laboratorio de Electronica", 2, 0},
	{"Logica Digital", 3, 0},
	{"Laboratorio Logica Digital", 2, 0},
	{"Geopolitica", 2, 0},
	{"Electiva I", 2, 0},
},
 8, 7, {
	 {"Maquinas Electricas II", 3, 0},
	 {"Laboratorio de Maquinas Electricas", 2, 0},
	 {"Control I", 3, 0},
	 {"Canalizaciones Electricas", 3, 0},
	 {"Termodinamica", 2, 0},
	 {"Introduccion a las Telecomunicaciones", 2, 1},
	 {"Sistemas de Senales", 2, 1},
	 {"Introduccion a la Metrologia", 2, 1},
	 {"Sistemas de Gestion de Calidad", 2, 1},
	 {"Introduccion a la Ingenieria Biomedica", 2, 0},
	 {"Introduccion a la Inteligencia Artificial", 2, 0},
},

9, 8, {
	{"Sistema de Potencia", 3, 0},
	{"Control II", 3, 0},
	{"Laboratorio de Control", 2, 0},
	{"Sistemas  Industriales", 3, 0},
	{"Electiva II", 2, 0},
	{"Comunicacion Analogica", 2, 1},
	{"Metrologia Dimensional", 2, 2},
	{"Biomecanica", 2, 3},
	},
10, 10, {
	{"Sistemas de Protecciones", 3, 0},
	{"Ingenieria Economica", 2, 0},
	{"Investigacion Basica", 2, 0},
	{"Sistemas de Distribucion", 3, 0},
	{"Comunicacion Digital", 2, 1},
	{"Antenas y Propagacion", 2, 1},
	{"Termometria", 2, 2},
	{"Metrologia Fisica y de Masa", 2, 2},
	{"Instrumentacion y Senales Biomedicas", 2, 3},
	{"Biomecanica", 2, 3},
	},
11, 10, {
	{"Mantenimiento y Pruebas Electricas", 3, 0},
	{"Administracion y Gerencia", 2, 0},
	{"Investigacion Aplicada", 3, 0},
	{"Legislacion Laboral", 2, 0},
	{"Telematica", 2, 1},
	{"Comunicaciones de Radiomicroondas", 2, 1},
	{"Metrologia de Fuerza, Presion y Torque", 2, 2},
	{"Tolerancias Geometricas y Dimensaionales", 2, 2},
	{"Materiales Biocompatibles", 2, 3},
	{"Mantenimiento en Sistemas Biotecnologicos", 2, 3},
},
12, 2, {
	{"Practica Profesional", 7, 0},
	{"Proyecto Socio-integrador", 6, 0},
},},


	 }



};
